language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "syhWtymPlYzrd0BzAW69jU19lWleDDeGTdOZQyG6qF7OeeccFut24EqZkR1ZpEFVYsB/Y/geMcH4YyrrOjuJxkptXI9iJS5qExlzBNFG9wywy3yUbLjxjAf6VsMEiVQRaSVPLHIgG3Uvln3rtbkF7Abt8lCGRgFuyxeMdqzZmHx0rvCYm/3FSirCiYvTVRsljRqxEOzraoQpy13egFK2Bk/bwNJ5VAKGcdj4mRZx/WrYxNQTAtiUaU4s/u8PdzrKmj0a+ZKz+oIGjTVrqC1f9O8yU6dBTgmM4fnCS6n2eDeBs7n9+wj+AFjvX8RDzK52QfDu1bDyzO7UZTfkklHk0m0zopVWX81oZKC6gMxwCzhrMoj+yvy2n3tlL5okE8o7Yz67usSeXsI4A6wv8/rmP6VTZXiKtKtdaqcykObpnwpnSGnkZ9YV0vDHopa0mCDBgpX1Un65QrVaqAnuaN6PCyplTdFUcCJ1VR2ApRD+l9OmYoWBQ11Dym1SZwez72oLP1CXZlwG0Egs6L+2nIb1Eicw+PIxl/TWdEAjTIbLhKFAshr2hxnrf9uPmplb/zgh6fxqeZDCqxZcimwpRI2k35YD0vTsR0T6PzMWSjDBX5jop9t0VsBI5rrJgSKEr9ga8WtSu8YU7+j06Wreoa3SrhvV6zlQt1XnddWAY9LIGOs="
